name: ForbiddenWordGame
version: '${version}'
main: org.voicerobotfight.VoiceRobotFight
api-version: '1.20'
libraries:
  - "net.kyori:adventure-api:4.17.0"
  - "net.kyori:adventure-platform-bukkit:4.3.2"
  - "net.kyori:adventure-text-minimessage:4.17.0"
  - 'com.fasterxml.jackson.core:jackson-databind:2.13.4'
commands:
  금칙어게임: